---
name: Test outputs

on:
  push:
    branches: '*'
  workflow_dispatch: 

jobs:
  make-output:
    runs-on: ubuntu-latest
    outputs:
      var_go: ${{ steps.out.outputs.var_go }}
    steps:
      - id: out
        shell: bash
        run: |
          echo var1="Hello world"
          echo "var_go=$var1" 
          echo "var_go=$var1" >> "$GITHUB_OUTPUT"
          echo "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
      - id: in
        shell: bash
        run: |
          echo "var_go: ${{ steps.out.outputs.var_go }}"
  check-needs:
    runs-on: ubuntu-latest
    needs: [make-output]
    steps:
      - name: debug
        shell: bash
        run: |
          echo var_go ${{ needs.make-output.outputs.var_go }}
          echo val2 ${{ 'true' }}
  check-if:
    runs-on: ubuntu-latest
    needs: make-output
    if: ${{ needs.make-output.outputs.var_go == 'Hello world' }}
    steps:
      - name: debug
        shell: bash
        run: echo YEEEEEESSSSSSSSSSSSSSSSSSS
  check-if2:
    runs-on: ubuntu-latest
    needs: make-output
    if: needs.make-output.outputs.var_go == 'Hello world'
    steps:
      - name: debug
        shell: bash
        run: echo YEEEEEESSSSSSSSSSSSSSSSSSS
  check-if3:
    runs-on: ubuntu-latest
    needs: make-output
    if: needs.make-output.outputs.var_go == 'Hello world'
    steps:
      - name: debug
        shell: bash
        run: echo YEEEEEESSSSSSSSSSSSSSSSSSS